%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function which produced movies of tissue evolution generated by the
% vertex model code. 
% Input: name of the file containing the output of the vertex model code 
% Output: A folder containing tiff images of the tissue at evey timepoint
% (To view the tiff images as a movie simply drage and drop the folder into
% imageJ)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function CreateMovie(inputFileName,tension_bounds)
% if tension_bounds == 1, use min and max tension over full simulation
% if tension_bounds == 0, use min and max tension from final timepoint

close all

%Initialize 
addpath('CreateMovie_HelpperFunctions');   %add path to where the functions are located
outputFileName=strcat(inputFileName, '_movie'); 
mkdir(outputFileName)                   %make a folder to store tif images in 
fid = fopen(inputFileName);
name=inputFileName;
count = 0;
figure()
axis equal 

%Get maximum box size
[MaxLX, MaxLY, LX_VECT, LY_VECT] = FindMaxBoxSize(fid);

%Move to the begining of the txt file
frewind(fid);
currentPos = ftell(fid);

% CHANGE BY HSN: use this to store min and max tension across the full simulation.
MinTension = inf; 
MaxTension = -inf;


%Loop through each timepoint and create an image of the tissue at that time
while (true)
    %Read the file
    [V,E,BoxSize, currentPos] = ReadSimulationOutput(fid, currentPos); 
    
    %If you have reached the end of the file stop 
    if currentPos == -2  %check end of file
        break
    end
    
    %Make the perodic boundary conditions 
    [~,Epbc] = MakePBC(V,E,BoxSize);
    % estimate min and max tension -- see comment above for tension_bounds
    if (tension_bounds == 1)
        MinTension = min(MinTension, min(Epbc.tension));
        MaxTension = max(MaxTension, max(Epbc.tension));
    else
        MinTension = min(Epbc.tension);
        MaxTension = max(Epbc.tension);
    end
end
% if all tensions the same, definite a finite range for colorbar
if (MinTension == MaxTension)
    MinTension = MaxTension - 1;
end

%Move to the begining of the txt file
frewind(fid);
currentPos = ftell(fid);

%Loop through each timepoint and create an image of the tissue at that time
while (true)
    %Read the file
    [V,E,BoxSize, currentPos] = ReadSimulationOutput(fid, currentPos); 
    
    %If you have reached the end of the file stop 
    if currentPos == -2  %check end of file
        break
    end
    
    %Make the perodic boundary conditions 
    [Vpbc,Epbc] = MakePBC(V,E,BoxSize);
    
    %Make a plot 
    clf
    %PlotSimulationOutput(Vpbc,Epbc,BoxSize,MaxLX,MaxLY,MinTension,MaxTension)
    PlotSimulationOutput(Vpbc,Epbc,BoxSize,MaxLX,MaxLY,0.5,3.8)

    %Save the plot as a tiff image 
    disp(['Generating frame ', num2str(count)]);
    framename=strcat(outputFileName,'/frame_',num2str(count,'%03d'),'.tif');
    imagewd = getframe(gcf); 
    imwrite(imagewd.cdata,framename,'tif','Resolution',100);

    count = count + 1;
    
end

% plot box size over time
figure; plot(LX_VECT);
ylabel('LX')
figure; plot(LY_VECT);
ylabel('LY')
figure; plot(LX_VECT.*LY_VECT);
ylabel('LX * LY')

%Close the file and exit 
fclose(fid);