%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function which produces movies of tissue evolution generated by the
% vertex model code.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function FindThreefoldVertexAndCables(inputFileName)

%% ==========================================================
% INITIALIZE
%% ==========================================================

close all;

numberOfCables = [];
numberOfThreeFold = [];
time = [];

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(scriptDir);

inputFile = fullfile(projectRoot,'input_files',inputFileName); 

underScoreIndexing = strfind(inputFileName,'_');
relevantFilePortion = inputFileName(1:underScoreIndexing(9)); 
folderOutputName = [relevantFilePortion 'visualization'];

fid = fopen(inputFile);
count = 0;
currentPos = 0;

% Open output files
outputDir = fullfile(projectRoot,"visualization_files",folderOutputName,'threefold_nucleation_vertices.txt'); 
fidOut = fopen(outputDir,'w');

cablesOutputDir = fullfile(projectRoot,"visualization_files",folderOutputName,'cables_over_time.txt');
fidCables = fopen(cablesOutputDir,'w');

while true

    [V,E,~,currentPos,~,~, currenttime, ~] = ReadSimulationOutput(fid,currentPos);

    if currentPos == -2
        break
    end

    ids = [];
    cablesThisTime = {};
    numberOfNucleations = 0;

    for i = 1:length(V.id)
        if V.Nucleation1(i) && V.Nucleation2(i) && V.Nucleation3(i)
            ids(end+1) = V.id(i);
        end
        
        if V.Nucleation1(i) || V.Nucleation2(i) || V.Nucleation3(i)
            numberOfNucleations = numberOfNucleations + 1;
        end
    end
    
    overNucleated = 3.0*numberOfNucleations > length(V.id);

    if(~overNucleated)
        for i = 1:length(V.id)
            cableIds = GetLongestChain(V, E, V.id(i));
    
            if numel(cableIds) > 2
                cablesThisTime{end+1} = cableIds;
            end
        end
        cablesThisTime = ReduceCable(cablesThisTime);
    end
 

    if ~isempty(ids)
        fprintf(fidOut, '%.6f ', currenttime);
        fprintf(fidOut, '%d ', ids);
        fprintf(fidOut, '\n');
    end

    if ~isempty(cablesThisTime)
        for j = 1:numel(cablesThisTime)
            fprintf(fidCables, '%.6f ', currenttime);
            idscable = cablesThisTime{j};
            idText = strjoin(string(idscable), ', ');
            fprintf(fidCables, '[%s]\n', idText);
        end
        fprintf(fidOut, '\n');
    end

    if isempty(cablesThisTime)
        numberOfCables = [numberOfCables, 0];
    else
        numberOfCables = [numberOfCables, numel(cablesThisTime)];
    end

    if isempty(ids)
        numberOfThreeFold = [numberOfThreeFold, 0];
    else
        numberOfThreeFold = [numberOfThreeFold, numel(ids)];
    end
    
    time = [time, currenttime];

end

fig = figure();


plot(time, numberOfThreeFold, 'r-', 'LineWidth', 1.5)
hold on
plot(time, numberOfCables, 'b-', 'LineWidth', 1.5)
hold off

xlabel('Time (s)')
ylabel('Count') 
title('Number of Threefold Verticies and Cables')
legend('Threefold Vertices', 'Cables', 'Location', 'best')
grid on

nameFig = 'CableAndThreefoldCount';
outputDir = fullfile(projectRoot,"visualization_files",folderOutputName,nameFig); 
saveas(fig,outputDir,'png'); 

disp('Cables and Threefold Found + .txt and graph saved');

fclose(fidOut);
fclose(fidCables);

end

function cableIds = GetLongestChain(V, E, vertexId, visitedIds)
    if nargin < 4
        visitedIds = [];
    end

    % Stop if we've already seen this vertex
    if any(visitedIds == vertexId)
        cableIds = [];
        return
    end

    % Mark current vertex as visited
    visitedIds = [visitedIds, vertexId];

    nucleatedNeighborIds = GetNucleatedNeighbors(V, E, vertexId);

    % Remove anything already visited
    nucleatedNeighborIds = nucleatedNeighborIds(~ismember(nucleatedNeighborIds, visitedIds));

    if isempty(nucleatedNeighborIds)
        cableIds = vertexId;
        return
    end

    cableIds = vertexId;

    for id = nucleatedNeighborIds
        tempCable = [vertexId, GetLongestChain(V, E, id, visitedIds)];
        if numel(tempCable) > numel(cableIds)
            cableIds = tempCable;
        end
    end
end

function nucleatedNeighborIds = GetNucleatedNeighbors(V, E, vertexId)
% Returns nucleated neighboring vertex ids for a given vertex id.
% If the vertex itself is not nucleated, returns [].

nucleatedNeighborIds = [];

vertexIndex = find(V.id == vertexId, 1, 'first');
if isempty(vertexIndex)
    return
end

isSelfNucleated = V.Nucleation1(vertexIndex) || ...
                  V.Nucleation2(vertexIndex) || ...
                  V.Nucleation3(vertexIndex);

if ~isSelfNucleated
    return
end

edgeMask = (E.vertex1 == vertexId) | (E.vertex2 == vertexId);
neighborIds = unique([E.vertex1(edgeMask); E.vertex2(edgeMask)]);
neighborIds(neighborIds == vertexId) = [];

if isempty(neighborIds)
    return
end

neighborIndices = find(ismember(V.id, neighborIds));
isNeighborNucleated = V.Nucleation1(neighborIndices) | ...
                      V.Nucleation2(neighborIndices) | ...
                      V.Nucleation3(neighborIndices);

nucleatedNeighborIds = V.id(neighborIndices(isNeighborNucleated));
nucleatedNeighborIds = nucleatedNeighborIds(:).';
end

function reducedCables = ReduceCable(cablesThisTime)
    % Keep only the longest cable associated with each vertex.
    % If multiple vertices pick the same cable, keep one copy.

    if isempty(cablesThisTime)
        reducedCables = {};
        return
    end

    % Normalize every cable to a row vector so concatenation is safe.
    normalizedCables = cellfun(@(c) c(:).', cablesThisTime, 'UniformOutput', false);

    % Collect every vertex that appears in any cable.
    allVertexIds = unique([normalizedCables{:}]);

    keepCable = false(1, numel(normalizedCables));

    for vertexId = allVertexIds
        cableMatches = find(cellfun(@(c) any(c == vertexId), normalizedCables));

        if isempty(cableMatches)
            continue
        end

        cableLengths = cellfun(@numel, normalizedCables(cableMatches));
        [~, longestIdx] = max(cableLengths);

        keepCable(cableMatches(longestIdx)) = true;
    end

    reducedCables = normalizedCables(keepCable);

    % Remove exact duplicates if the same cable was selected by multiple vertices.
    if numel(reducedCables) > 1
        signatures = cellfun(@(c) sprintf('%d_', c), reducedCables, 'UniformOutput', false);
        [~, uniqueIdx] = unique(signatures, 'stable');
        reducedCables = reducedCables(uniqueIdx);
    end
end