%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function which produces movies of tissue evolution generated by the
% vertex model code.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function FollowVertex(inputFileName,tension_bounds, vertexIds)

close all;

ploteverynumframes = 10;

if nargin < 3 || isempty(vertexIds)
    vertexIds = [];
end
vertexIds = unique(vertexIds(:).');

if nargin == 0
    disp('No file given using default')
    inputFileName = '/Users/rafaelvolkamer-pastor/Library/CloudStorage/GoogleDrive-volkamerr@carleton.edu/My Drive/Summer Experiences/Michigan Biophysics REU/vertexModelSummer2026/vertexModelSummer2026/input_files/RFB_NbPts_0200_rng_2031_pot_ani_lim_320_relaxed_out.txt';
    tension_bounds = 0;
end

%% ==========================================================
% INITIALIZE
%% ==========================================================
addpath('CreateMovie_HelpperFunctions');
outputFileName = strcat(inputFileName,'_movie');
mkdir(outputFileName)

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(scriptDir);

inputFile = fullfile(projectRoot,'input_files',inputFileName); 

underScoreIndexing = strfind(inputFileName,'_');
relevantFilePortion = inputFileName(1:underScoreIndexing(9)); 
folderOutputName = [relevantFilePortion 'visualization'];

fid = fopen(inputFile);
count = 0;
timeHistory = [];
trackedEdgeIds = [];
trackedEdgeColors = [];
edgeTensionHistory = [];
totalTime = 0;

fig = figure(1);
fig.Position = [100 100 1000 600];
 

%% ==========================================================
% GET MAX BOX SIZE
%% ==========================================================
[MaxLX, MaxLY, LX_VECT, LY_VECT] = FindMaxBoxSize(fid);
frewind(fid);
currentPos = ftell(fid);

%% ==========================================================
% (OPTIONAL) COMPUTE GLOBAL TENSION RANGE
%% ==========================================================
MinTension = inf;
MaxTension = -inf;

while true
    [V,E,BoxSize,currentPos,TENSION_THRESHOLD,RuntimeProperties,currentTime, remodelingTension] = ReadSimulationOutput(fid,currentPos);

    if currentPos == -2
        break
    end

    [~,Epbc] = MakePBC(V,E,BoxSize);

    MinTension = min(MinTension,min(Epbc.tension));
    MaxTension = max(MaxTension,max(Epbc.tension));

    totalTime = RuntimeProperties.TotalTime;
end

if MinTension == MaxTension
    MinTension = MaxTension - 1;
end

%% ==========================================================
% REWIND FILE
%% ==========================================================
frewind(fid);
currentPos = ftell(fid);

%% ==========================================================
% MAIN MOVIE LOOP
%% ==========================================================

% Choose your name
vertexLabel = strjoin(string(vertexIds), '_');
movieName = sprintf('vertexvideo_vid%s', vertexLabel);
outputFileName = strcat(movieName,'_movie');
outputDir = fullfile(projectRoot,'visualization_files',folderOutputName);
%tifFolder = fullfile(outputDir,"Vertex_Images");
movieFile = fullfile(outputDir,outputFileName);
movieObj = VideoWriter(movieFile, "MPEG-4");

%mkdir(tifFolder);

%if RuntimeProperties.TotalTime/RuntimeProperties.TimeInterval < 100
   % movieObj.Duration = 1000; 
%else
   % movieObj.FrameRate = 20; 
%end

open(movieObj);

while true

    if ~isgraphics(fig)
        break
    end

    [V,E,BoxSize,currentPos,TENSION_THRESHOLD,RuntimeProperties,currentTime, remodelingTension] = ReadSimulationOutput(fid,currentPos);

    if currentPos == -2
        break
    end

    [Vpbc,Epbc] = MakePBC(V,E,BoxSize);

    if isempty(trackedEdgeIds)
        trackedEdgeIds = GetTrackedEdgeIds(Epbc, vertexIds);
        trackedEdgeColors = GetTrackedEdgeColors(numel(trackedEdgeIds));
    end

    currentTensions = GetTrackedEdgeTensions(Epbc, trackedEdgeIds);
    edgeTensionHistory(end+1, :) = currentTensions;
    timeHistory(end+1,1) = currentTime;

    %% ---------------- PLOT FRAME ----------------
    if(mod(count, ploteverynumframes) == 0)
        clf(fig)
        PlotSimulationOutput_Vertex( ...
            Vpbc,Epbc,BoxSize,MaxLX,MaxLY,TENSION_THRESHOLD, vertexIds, ...
            currentTensions, timeHistory, trackedEdgeIds, trackedEdgeColors, edgeTensionHistory, totalTime, MinTension, MaxTension, remodelingTension);
    
        drawnow;
    
        if ~isgraphics(fig)
            break
        end
    
        %% ---------------- SAVE FRAME ----------------
        disp(['Generating frame ',num2str(count)])
        
    
        %framename = strcat(tifFolder,'/frame_',num2str(count,'%03d'),'.tif');
        % set(fig,'Resize','off'); 
        % fig.Position(3) = 1920;
        % fig.Position(4) = 1080;
        imagewd = getframe(fig);
        %imwrite(imagewd.cdata,framename,'tif','Resolution',100);
        movieObj.writeVideo(imagewd); 
    
        %PlotVertexTensionHistoryFigure(timeHistory, edgeTensionHistory, trackedEdgeIds, totalTime, vertexId, MinTension, MaxTension);
    
       
    end
     count = count + 1;
end

movieObj.close;

%% ==========================================================
% BOX SIZE DIAGNOSTICS
%% ==========================================================
figure; plot(LX_VECT); ylabel('LX')
figure; plot(LY_VECT); ylabel('LY')
figure; plot(LX_VECT.*LY_VECT); ylabel('LX * LY')

%% ==========================================================
% CLOSE FILE
%% ==========================================================
fclose(fid);
fig = figure();
PlotVertexTensionHistoryFigure(timeHistory, edgeTensionHistory, trackedEdgeIds, trackedEdgeColors, vertexIds, MinTension, MaxTension, TENSION_THRESHOLD, remodelingTension);

if isempty(vertexIds)
    nameFig = 'vertexTensionPlot_vidnone';
else
    vertexLabel = strjoin(string(vertexIds), '_');
    nameFig = sprintf('vertexvideo_vid%s', vertexLabel);
end
outputDir = fullfile(projectRoot,"visualization_files",folderOutputName,nameFig); 
saveas(fig,outputDir,'png'); 

end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PLOTTING FUNCTION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function PlotSimulationOutput_Vertex(V,E,BoxSize,xMax,yMax,TENSION_THRESHOLD, vertexIds, currentTensions, timeHistory, trackedEdgeIds, trackedEdgeColors, edgeTensionHistory, totalTime, minTension, maxTension, remodelingTension)

%% ======================================
% COLORS
%% ======================================
UNTRACKED_COLOR = [0.65 0.65 0.65];
TRACKED_WIDTH = 2.4;
UNTRACKED_WIDTH = 1.0;

if isempty(trackedEdgeIds)
    trackedEdgeIds = GetTrackedEdgeIds(E, vertexIds);
    trackedEdgeColors = GetTrackedEdgeColors(numel(trackedEdgeIds));
end

%% ======================================
% PLOT EDGES
%% ======================================
subplot(1,3,1);
PlotVertexNeighborhood(V,E,BoxSize,xMax,yMax,TENSION_THRESHOLD, vertexIds, false, trackedEdgeIds, trackedEdgeColors, UNTRACKED_COLOR, TRACKED_WIDTH, UNTRACKED_WIDTH);

subplot(1,3,2);
PlotVertexNeighborhood(V,E,BoxSize,xMax,yMax,TENSION_THRESHOLD, vertexIds, true, trackedEdgeIds, trackedEdgeColors, UNTRACKED_COLOR, TRACKED_WIDTH, UNTRACKED_WIDTH);

subplot(1,3,3);
PlotVertexTensionBarChart(currentTensions, trackedEdgeIds, vertexIds, trackedEdgeColors, minTension, maxTension, TENSION_THRESHOLD, remodelingTension);


end


function edgeIds = GetTrackedEdgeIds(E, vertexIds)

edgeids = find(ismember(E.vertex1, vertexIds) | ismember(E.vertex2, vertexIds));
edgeIds = unique(E.id(edgeids));
edgeIds = edgeIds(:).';
edgeIds = sort(edgeIds);

end


function tensions = GetTrackedEdgeTensions(E, trackedEdgeIds)

tensions = nan(1, numel(trackedEdgeIds));

for i = 1:numel(trackedEdgeIds)
    matchIndex = find(E.id == trackedEdgeIds(i), 1, 'first');
    if ~isempty(matchIndex)
        tensions(i) = E.tension(matchIndex);
    end
end

end


function trackedEdgeColors = GetTrackedEdgeColors(numTrackedEdges)

if numTrackedEdges == 0
    trackedEdgeColors = zeros(0, 3);
else
    trackedEdgeColors = lines(numTrackedEdges);
end

end


function PlotVertexTensionHistoryFigure(timeHistory, edgeTensionHistory, trackedEdgeIds, trackedEdgeColors, vertexIds, minTension, maxTension, TENSION_THRESHOLD, remodelingTension)

hold on;

for i = 1:numel(trackedEdgeIds)
    if size(edgeTensionHistory, 2) < i
        continue
    end
    plot(timeHistory, edgeTensionHistory(:, i), 'Color', trackedEdgeColors(i,:), 'LineWidth', 1.5, ...
        'DisplayName', sprintf('Edge %d', trackedEdgeIds(i)));
end

xlabel('Time (s)')
ylabel('Tension')
title(sprintf('Tracked edge tensions for vertices %s', strjoin(string(vertexIds), ', ')))
grid on

if isfinite(minTension) && isfinite(maxTension) && minTension ~= maxTension
    ylim([minTension, maxTension]);
end

yline(TENSION_THRESHOLD, 'b--', 'LineWidth', 2);
yline(remodelingTension, 'r--', 'LineWidth', 2);

if ~isempty(trackedEdgeIds)
    legend('Location', 'bestoutside');
end

hold off;

end


function PlotVertexNeighborhood(V,E,BoxSize,xMax,yMax,TENSION_THRESHOLD, vertexIds, zoomedIn, trackedEdgeIds, TRACKED_COLORS, UNTRACKED_COLOR, TRACKED_WIDTH, UNTRACKED_WIDTH)

hold on;

edgeids = find(ismember(E.vertex1, vertexIds) | ismember(E.vertex2, vertexIds));
targetIndices = find(ismember(V.id, vertexIds));
neighborIds = unique([E.vertex1(edgeids); E.vertex2(edgeids)]);
neighborIds(ismember(neighborIds, vertexIds)) = [];
neighborIndices = find(ismember(V.id, neighborIds));

for edgeIndex = edgeids'
    vind1 = find(V.id == E.vertex1(edgeIndex),1,'first');
    vind2 = find(V.id == E.vertex2(edgeIndex),1,'first');

    if isempty(vind1) || isempty(vind2)
        continue
    end

    trackedIndex = find(trackedEdgeIds == E.id(edgeIndex), 1, 'first');
    if isempty(trackedIndex)
        edge_color = UNTRACKED_COLOR;
        lw = UNTRACKED_WIDTH;
    else
        edge_color = TRACKED_COLORS(mod(trackedIndex - 1, size(TRACKED_COLORS, 1)) + 1, :);
        lw = TRACKED_WIDTH;
    end

    line([V.x(vind1),V.x(vind2)], ...
         [V.y(vind1),V.y(vind2)], ...
         'Color', edge_color, ...
         'LineWidth', lw);
end

if ~isempty(neighborIndices)
    plot(V.x(neighborIndices), V.y(neighborIndices), 'o', ...
        'MarkerSize', 3, ...
        'MarkerFaceColor', [0.9 0.9 0.9], ...
        'LineWidth', 1.0);
end

if ~isempty(targetIndices)
    plot(V.x(targetIndices), V.y(targetIndices), 'o', ...
        'MarkerSize', 4, ...
        'MarkerFaceColor', [1 1 0], ...
        'MarkerEdgeColor', 'k');

    for targetIndex = targetIndices(:).'
        if all(~isnan([V.Nucleation1(targetIndex), V.Nucleation2(targetIndex), V.Nucleation3(targetIndex)])) && ...
                (V.Nucleation1(targetIndex) || V.Nucleation2(targetIndex) || V.Nucleation3(targetIndex))
            phillip = linspace(0,2*pi,100);
            r = 1;
            x = r * cos(phillip) + V.x(targetIndex);
            y = r * sin(phillip) + V.y(targetIndex);
            plot(x,y,'Color',[1 1 1],'LineWidth',2.5);
        end
    end
end

set(gca,'Color',[128 128 128]/256);
set(gca,'XTick',[]);
set(gca,'YTick',[]);
set(gca,'DataAspectRatio',[1 1 1]);

if zoomedIn
    localIndices = unique([targetIndices; neighborIndices]);
    localIndices = localIndices(localIndices > 0);

    if ~isempty(localIndices)
        xs = V.x(localIndices);
        ys = V.y(localIndices);
        padX = max(1, 0.25 * max(1, max(xs) - min(xs)));
        padY = max(1, 0.25 * max(1, max(ys) - min(ys)));
        set(gca, 'XLim', [min(xs) - padX, max(xs) + padX], ...
                 'YLim', [min(ys) - padY, max(ys) + padY]);
    else
        set(gca, 'XLim', [-5 xMax], ...
                 'YLim', [-5 yMax]);
    end
else
    LX = BoxSize(1);
    LY = BoxSize(2);

    line([0 LX],[0 0],'Color','k','LineWidth',1);
    line([0 LX],[LY LY],'Color','k','LineWidth',1);
    line([0 0],[0 LY],'Color','k','LineWidth',1);
    line([LX LX],[0 LY],'Color','k','LineWidth',1);

    set(gca,'XLim',[-5 xMax], ...
             'YLim',[-5 yMax]);
end

title(sprintf('Vertices %s', strjoin(string(vertexIds), ', '))); 

hold off;

end


function PlotVertexTensionBarChart(currentTensions, trackedNeighborIds, vertexIds, TRACKED_COLORS, minTension, maxTension, TENSION_THRESHOLD, remodelingTension)

hold on;

bars = bar(1:numel(trackedNeighborIds), currentTensions, 0.65, 'FaceColor', 'flat');

for i = 1:numel(trackedNeighborIds)
    bars.CData(i,:) = TRACKED_COLORS(mod(i - 1, size(TRACKED_COLORS,1)) + 1, :);
end

xlabel('Tracked edge');
ylabel('Tension');
title(sprintf('Vertices %s current edge tensions', strjoin(string(vertexIds), ', ')));

set(gca, 'XTick', 1:numel(trackedNeighborIds), ...
    'XTickLabel', compose('%d', trackedNeighborIds));

yline(TENSION_THRESHOLD, 'b--', 'LineWidth', 2);
yline(remodelingTension, 'r--', 'LineWidth', 2);
if isfinite(minTension) && isfinite(maxTension) && minTension ~= maxTension
    ylim([minTension, maxTension]);
end

grid on;

hold off;

end