%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function which produces movies of tissue evolution generated by the
% vertex model code.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function CreateMovie_m(inputFileName,tension_bounds)

if nargin == 0
    disp('No arguments given using default')
    inputFileName = '/Users/ibrahim/Documents/Lubensky_Group/gitCode/newDynamicTensions-mainUpdated/input_files/RFB_NbPts_0200_rng_2031_pot_ani_lim_320_relaxed_out.txt';
    tension_bounds = 0;
end

%% ==========================================================
% INITIALIZE
%% ==========================================================
addpath('CreateMovie_HelpperFunctions');
outputFileName = strcat(inputFileName,'_movie');
mkdir(outputFileName)

fid = fopen(inputFileName);
count = 0;

figure();

%% ==========================================================
% USER PARAMETER
%% ==========================================================
TENSION_THRESHOLD = 2.0;   % <<< CHANGE THIS VALUE

%% ==========================================================
% GET MAX BOX SIZE
%% ==========================================================
[MaxLX, MaxLY, LX_VECT, LY_VECT] = FindMaxBoxSize(fid);
frewind(fid);
currentPos = ftell(fid);

%% ==========================================================
% (OPTIONAL) COMPUTE GLOBAL TENSION RANGE
%% ==========================================================
MinTension = inf;
MaxTension = -inf;

while true
    [V,E,BoxSize,currentPos,TENSION_THRESHOLD] = ReadSimulationOutput(fid,currentPos);

    if currentPos == -2
        break
    end

    [~,Epbc] = MakePBC(V,E,BoxSize);

    if tension_bounds == 1
        MinTension = min(MinTension,min(Epbc.tension));
        MaxTension = max(MaxTension,max(Epbc.tension));
    else
        MinTension = min(Epbc.tension);
        MaxTension = max(Epbc.tension);
    end
end

if MinTension == MaxTension
    MinTension = MaxTension - 1;
end

%% ==========================================================
% REWIND FILE
%% ==========================================================
frewind(fid);
currentPos = ftell(fid);

%% ==========================================================
% MAIN MOVIE LOOP
%% ==========================================================

outputFileName = strcat(inputFileName,'_movie');
mkdir(outputFileName)

movieFile = fullfile(outputFileName,'movie.mp4');
movieObj = VideoWriter(movieFile,'MPEG-4');
open(movieObj);


while true

    [V,E,BoxSize,currentPos,TENSION_THRESHOLD] = ReadSimulationOutput(fid,currentPos);

    if currentPos == -2
        break
    end

    [Vpbc,Epbc] = MakePBC(V,E,BoxSize);

    %% ---------------- PLOT FRAME ----------------
    clf

    PlotSimulationOutput_modified( ...
        Vpbc,Epbc,BoxSize,MaxLX,MaxLY,TENSION_THRESHOLD);

    %% ---------------- SAVE FRAME ----------------
    disp(['Generating frame ',num2str(count)])

    framename = strcat(outputFileName, ...
        '/frame_',num2str(count,'%03d'),'.tif');
    fig = gcf; 
    fig.Position(3) = 840; 
    imagewd = getframe(fig);
    imwrite(imagewd.cdata,framename,'tif','Resolution',100);
    movieObj.writeVideo(imagewd); 

    count = count + 1;
end

movieObj.close;

%% ==========================================================
% BOX SIZE DIAGNOSTICS
%% ==========================================================
figure; plot(LX_VECT); ylabel('LX')
figure; plot(LY_VECT); ylabel('LY')
figure; plot(LX_VECT.*LY_VECT); ylabel('LX * LY')

%% ==========================================================
% CLOSE FILE
%% ==========================================================
fclose(fid);

end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PLOTTING FUNCTION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function PlotSimulationOutput_modified( ...
    V,E,BoxSize,xMax,yMax,TENSION_THRESHOLD)

hold on;

%% ======================================
% COLORS
%% ======================================
HIGH_COLOR = [1 0 0];      % red
LOW_COLOR  = [0 0 1];      % blue
HIGH_WIDTH = 2.5;
LOW_WIDTH  = 1.0;

%% ======================================
% PLOT EDGES
%% ======================================
N = size(E.id,1);

for i = 1:N

    vind1 = find(V.id == E.vertex1(i));
    vind2 = find(V.id == E.vertex2(i));

    if isempty(vind1) || isempty(vind2)
        continue
    end

    tension = E.tension(i);

    if tension >= TENSION_THRESHOLD
        edge_color = HIGH_COLOR;
        lw = HIGH_WIDTH;
    else
        edge_color = LOW_COLOR;
        lw = LOW_WIDTH;
    end

    line([V.x(vind1),V.x(vind2)], ...
         [V.y(vind1),V.y(vind2)], ...
         'Color', edge_color, ...
         'LineWidth', lw);
end

%% ======================================
% PLOT VERTEXES
%% ======================================
N = length(V.Nucleation1);

for i = 1:N
    vertexX = V.x(i);
    vertexY = V.y(i);
    if(isnan(V.Nucleation1(i)) || isnan(V.Nucleation2(i)) || isnan(V.Nucleation3(i)))
        break
    end
    if(V.Nucleation1(i) || V.Nucleation2(i) || V.Nucleation3(i))
        %% viscircles([vertexX vertexY], 1);
        phillip = linspace(0,2*pi,100);
        r = 1; 
        x = r * cos(phillip) + vertexX; 
        y = r * sin(phillip) + vertexY;
        plot(x,y,Color=[1 1 1],LineWidth=2.5); 
    end

end

%% ======================================
% DRAW BOX
%% ======================================
LX = BoxSize(1);
LY = BoxSize(2);

line([0 LX],[0 0],'Color','k','LineWidth',1);
line([0 LX],[LY LY],'Color','k','LineWidth',1);
line([0 0],[0 LY],'Color','k','LineWidth',1);
line([LX LX],[0 LY],'Color','k','LineWidth',1);

%% ======================================
% AXIS SETTINGS
%% ======================================
ha = gca;

set(gca,'Color',[128 128 128]/256);
set(ha,'XLim',[-5 xMax], ...
       'YLim',[-5 yMax], ...
       'DataAspectRatio',[1 1 1]);

set(ha,'XTick',[]);
set(ha,'YTick',[]);

%% ======================================
% LEGEND (FIXED — NO AUTO SCANNING)
%% ======================================

hHigh = plot(nan,nan,'-','Color',HIGH_COLOR,'LineWidth',2.5);
hLow  = plot(nan,nan,'-','Color',LOW_COLOR,'LineWidth',1);

title('SimulationVideo'); 
legend([hHigh hLow], ...
    {'T > Threshold','T < Threshold'}, ...
    'TextColor','b', ...
    'Location','southoutside');

hold off;

end